---
name: DayandNight
version: 1.2.6-STABLE
main: TheAMDGuy\DayandNight\Main
api: 3.0.0
commands:
  day:
    description: Sets the time to day.
    usage: /day
    aliases:
      - tsd
  night:
    description: Sets the time to night.
    usage: /night
    aliases:
      - tsn
  set:
    description: Sets the time to sunset.
    usage: /set
    aliases:
      - tss
  rise:
    description: Sets the time to sunrise.
    usage: /rise
    aliases:
      - tsr
  midday:
    description: Sets the time to midday.
    usage: /midday
    aliases:
      - tsmd
  midnight:
    description: Sets the time to midnight.
    usage: /midnight
    aliases:
      - tsmn
  dayandnight:
    description: Informates about all avaiable DayandNight commands.
    usage: /dayandnight
    aliases:
      - dan
      - daninfo
      - danhelp
permissions:
  dayandnight:
    default: op
    description: Permission for all DayandNight commands.
    children:
      dayandnight.day:
        default: op
        description: Permission to set the time to day.
      dayandnight.night:
        default: op
        description: Permission to set the time to night.
      dayandnight.set:
        default: op
        description: Permission to set the time to set.
      dayandnight.rise:
        default: op
        description: Permission to set the time to rise.
      dayandnight.midday:
        default: op
        description: Permission to set the time to midday.
      dayandnight.midnight:
        default: op
        description: Permission to set the time to midnight.
      dayandnight.info:
        default: op
        description: Permission to get all avaiable DayandNight commands.
...
